app = "packing-list-realtime"   # your app name
primary_region = "lhr"

[build]
  dockerfile = "./Dockerfile"

[env]
  PORT = "1234"                 # redundant with Dockerfile, but fine

[[services]]
  protocol = "tcp"
  internal_port = 1234

  [[services.ports]]
    port = 80
    handlers = ["http"]
  [[services.ports]]
    port = 443
    handlers = ["tls","http"]

  [[services.tcp_checks]]
    interval = "15s"
    timeout  = "2s"
    grace_period = "10s"

[[mounts]]
  source = "ydata"
  destination = "/ydata"
